'use strict'

/*
 * adonis-framework
 *
 * (c) Harminder Virk <virk@adonisjs.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
*/

/**
 * The logger class is used to record logs through-out the
 * application. The class instance is generated by the
 * @ref('LoggerFacade') class.
 *
 * @group Core
 *
 * @class Logger
 * @constructor
 */
class Logger {
  constructor (driver) {
    /**
     * The driver in use for logging
     *
     * @type {Object}
     *
     * @attribute driver
     */
    this.driver = driver
  }

  /**
   * Hash of log levels used by Logger
   * internally.
   *
   * @attribute levels
   *
   * @return {Object}
   */
  get levels() {
    return {
      severe: 0,
      warning: 1,
      info: 2,
      fine: 3,
      verbose: 4,
      debug: 5,
    };
  }

  /**
   * The active log level for the logger driver.
   *
   * @attribute level
   *
   * @return {String}
   */
  get level () {
    return this.driver.level
  }

  /**
   * Update log level for the logger driver
   *
   * @param  {String} level
   *
   * @return {void}
   */
  set level (level) {
    this.driver.level = level
  }

  /**
   * Log a new message with given level. The configured
   * driver will be used to log the messages.
   *
   * @method log
   *
   * @param  {String}    level
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  log(level, message, ...options) {
    this.driver.log(level, message, ...options);
  }

  /**
   * Log a message with severe level.
   *
   * @method severe
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  severe(message, ...options) {
    this.log(0, message, ...options);
  }

  /**
   * Log a message with fine level.
   *
   * @method fine
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  fine(message, ...options) {
    this.log(3, message, ...options);
  }

  /**
   * Log a message with verbose level.
   *
   * @method verbose
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  verbose(message, ...options) {
    this.log(4, message, ...options);
  }

  /**
   * Log a message with debug level.
   *
   * @method debug
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  debug(message, ...options) {
    this.log(5, message, ...options);
  }

  /**
   * Log a message with info level.
   *
   * @method info
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  info(message, ...options) {
    this.log(2, message, ...options);
  }

  /**
   * Log a message with notice level.
   *
   * @method notice
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  notice(message, ...options) {
    this.log(1, message, ...options);
  }

  /**
   * Log a message with warning level.
   *
   * @method warning
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  warning(message, ...options) {
    this.log(1, message, ...options);
  }

  /**
   * Log a message with error level.
   *
   * @method error
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  error(message, ...options) {
    this.log(0, message, ...options);
  }

  /**
   * Log a message with critical level.
   *
   * @method crit
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  crit(message, ...options) {
    this.log(0, message, ...options);
  }

  /**
   * Log a message with alert level.
   *
   * @method alert
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  alert(message, ...options) {
    this.log(0, message, ...options);
  }

  /**
   * Log a message with emergency level.
   *
   * @method emerg
   *
   * @param  {String}    message
   * @param  {...Spread} options
   *
   * @return {void}
   */
  emerg(message, ...options) {
    this.log(0, message, ...options);
  }
}

module.exports = Logger;
